export const DefaultSettings = {
  NSFW: false,
  bandwidth: false,
  PTT: true,
  setBadge: false,
  streamPreview: false,
  fakePreview: "",
  noAFK: false,
  spotifyPremium: true,
  spotifyPause: true,
  verification: false,
  maxAccounts: true,
  clientThemes: true,
  clientThemeSettings: null,
  appIcons: true,
  plainFolderIcon: true,
  favIMG: true,
  ringtone: "sync",
  spam: false,
  voiceMessage: true,
  silenceLogger: false,
};
